# Problem 1 

In [4]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array0=np.array([10,2,1,5,3])
print(array1)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
array0.sort()
print(array1)

[10  2  1  5  3]
[ 1  2  3  5 10]


# Problem 2

In [41]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
array1=np.array([10,15,30,45,60])
print(array1)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array2=np.arange(5,16)
print(array2)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array3=np.arange(50,101,5)
print(array3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array4=np.zeros(10)
print(array4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array5=np.ones(10)
print(array5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
array6=np.linspace(0,100,5)
print(array6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
array7=np.random.randint(10,30,size=5)
print(array7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
array8=np.random.uniform(-1,1,size=10)
print(array8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris=np.random.randint(10,50,size=(3,5))
print(matris)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(matris.sum(axis=1))
print(matris.sum(axis=0))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(matris.max())
print(matris.min())
print(matris.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(matris.argmax())

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array13=np.arange(10,20)
print(array13)
print(array13[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(array13[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(matris[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(matris[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(matris[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(matris**2)
np.power(matris,2)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris2=np.random.randint(-50,50,size=(3,5))
print(matris2)

print((matris2>0)&(matris2%2==0))

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[11 19 13 13 21]
[ 0.72342984 -0.87078223 -0.60303185  0.31696875 -0.81360462 -0.28026648
  0.50823184 -0.25987944  0.22283646  0.77349231]
[[12 26 34 39 16]
 [21 21 12 13 21]
 [13 31 24 21 43]]
[127  88 132]
[46 78 70 73 80]
43
12
23.133333333333333
14
[10 11 12 13 14 15 16 17 18 19]
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[12 26 34 39 16]
12
[12 21 13]
[[ 144  676 1156 1521  256]
 [ 441  441  144  169  441]
 [ 169  961  576  441 1849]]
[[ 20 -14 -36   4  13]
 [-42  -7  -3 -49 -12]
 [-44  36  32  32  44]]
[[ True False False  True False]
 [False False False False False]
 [False  True  True  True  True]]
