# Problem 1

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 6 sayıdan oluşan matris üretin
matris= np.random.randint(0,10,6)
print(matris)
# 3 - matris'in boyutunu öğrenin
print(matris.ndim)
print(matris.shape)
# 4 - matris'i yeniden boyutlandırın
new= matris.reshape(2,3)
print(new)
# 5 - matris'in boyut sayısını öğrenin
print(new.ndim)
print(new.shape)

[3 1 0 4 7 6]
1
(6,)
[[3 1 0]
 [4 7 6]]
2
(2, 3)


# Problem 2

In [28]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris_2= np.arange(1,10,2)
print(matris_2)
# 2 - Oluşturduğunuz matrisi parçalayın
a,b,c= np.split(matris_2,[2,3])
print(a)
print(b)
print(c)
# 3 - Parçalanmış matrisleri birleştirin
np.concatenate([a,b,c])



[1 3 5 7 9]
[1 3]
[5]
[7 9]


array([1, 3, 5, 7, 9])

# Problem 3

In [30]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
"""rastgele 10 sayıdan oluştururken 2şer 2şer atlama kavramını anlamadım. Bu sorutu rkadaşlarıma soracağım."""
# 2 - matris'in özelliklerini inceleyin



'rastgele 10 sayıdan oluştururken 2şer 2şer atlama kavramını anlamadım. Bu sorutu rkadaşlarıma soracağım.'