**ASENKRON DERS KAYDI ÖZETİ VE ÇALIŞMALAR:**

In [2]:
#1.BÖLÜM:
import numpy as np
#Kütüphaneyi np olarak ekledim.

a=np.array([1,2,3,4]) 
# 1e 4 bir matrisin 1. satır dizinini yarattım.
b=np.array([2,3,4,5])
# 1e 4 bir matrisin 1. satır dizinini yarattım.
print(a*b)

# .reshape() ile dizinlerin boyutlarını değiştirebiliriz.

x=np.array([1,2,3,4,5,6,7,8,9])
multi= x.reshape(3,3)
print(multi)

# .shape() arrayin boyutlarını verir.

print(x.shape)
print(multi.shape)

# .ndim arraylarin boyut sayısını verir.

print(x.ndim)
print(multi.ndim)

[ 2  6 12 20]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(9,)
(3, 3)
1
2


**2.BÖLÜM:**

In [12]:

# .concatenate() ile sıralı birleştirme yapabiliriz.

x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10,11])
z= y.reshape(2,3)
print(z)
print(np.concatenate([x,y]))

a=np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a[0], a[1]]))

print(np.concatenate([z,z], axis=0))
# axis=0 ile satırları alt alta birleştirerek bir matris yapar.

print(np.concatenate([z,z], axis=1))
# axis=1 ile satırları yan yana birleştirerek bir matris yapar.

[[ 6  7  8]
 [ 9 10 11]]
[ 1  2  3  4  5  6  7  8  9 10 11]
[1 2 3 4 5 6]
[[ 6  7  8]
 [ 9 10 11]
 [ 6  7  8]
 [ 9 10 11]]
[[ 6  7  8  6  7  8]
 [ 9 10 11  9 10 11]]


In [16]:
#.split() ile array ayırma yapabiliriz.

m=np.array([1,2,3,4,5,6,7,8,9])
print(np.split(m,[3,6]))

a,b,c= np.split(m,[3,6])
print(f" {a}\n {b}\n {c}")

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
 [1 2 3]
 [4 5 6]
 [7 8 9]


In [3]:
# np.arange(start, stop, step):

np.arange(0,13,5)

array([ 0,  5, 10])

In [23]:
n= np.arange(16).reshape(4,4)
print(f"{n}\n")

# .vsplit(variable,[sayı]): Matrisi yatay olarak arraylere ayırır.
np.vsplit(n,[2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [24]:
# .hsplit(variable,[sayı]): Matrisi dikey olarak sayı kadar arraylere ayırır
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
# np.zeros(adet): Adet kadar O'lardan oluşan bir numpy dizisi oluşturmak için kullanılır.

# np.ones(adet): Adet kadar 1'lerden oluşan bir numpy dizisi oluşturmak için kullanılır.

In [10]:
# np.linspace(start, stop, elde edilecek adet sayı ):

np.linspace(0,200,5)

array([  0.,  50., 100., 150., 200.])

In [12]:
# np.random.randint(start, stop, adet)
np.random.randint(0,10,4)

array([9, 5, 5, 8])

In [15]:
array= np.arange(50)
print(array)

matris= array.reshape(5,10)
print(matris)

print(matris.sum(axis=0))
#axis=1 Aynı sütundakileri toplayıp sırayla yazıyor. 1 e 10 luk matris oldu. Çünkü 10 sütun vardı.

print(matris.sum(axis=1))
#axis=0 Aynı satırdakileri toplayıp sırayla yazıyor. 1 e 5 lik matris oldu. Çünkü 5 satır vardı.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[100 105 110 115 120 125 130 135 140 145]
[ 45 145 245 345 445]


In [18]:
#.ndim: Kaç boyutlu?
#.shape: Kaç a kaç matris?
# .size: Eleman sayısı?
#.dtype: Veri tipi

print(matris.ndim)
print(matris.shape)
print(matris.size)
print(matris.dtype)

2
(5, 10)
50
int64


In [23]:
#SORTING: .sort()

x=np.random.randint(1,10,5)
print(x)
x.sort()
print(x)

[6 9 5 1 1]
[1 1 5 6 9]


In [ ]:
#İndeksleme ve indeks işlemleri aynı listelerdeki gibi yapılabilir.

**3.BÖLÜM:**

In [ ]:
#np.substract(variable, sayı): çıkarma

#np.add(variable, sayı): toplama

#np.multiply(variable, sayı): çarpma

#np.divide(variable, sayı): bölme

#np.power(variable, sayı): üssünü alma

#np.mod(variable, sayı): mod alma

#np.absoluate(variable,): mutlak değer

#np.sin(derece): derecenin sinüs değerini verir

#np.log(değer): log değerin karşılığını verir



***2 Bilinmeyenli Denklem Çözümü***

In [24]:
# 5*x0 + x1= 12
# x0 + 3*x1= 10

a= np.array([[5,1],[1,3]])
b= np.array([12,10])
x=np.linalg.solve(a,b)
print(x)

[1.85714286 2.71428571]
